// Generated by CoffeeScript 1.6.2
(function() {
  jQuery.extend({
    slider: function(k, p) {
      var a, b, c, d, e, f, g, h, i, j, l, m, n, o;

      m = {
        slider: "<div id=\"slider\" style=\"position: relative; overflow: hidden\"></div>",
        wrapper: "<div id=\"sliderWrapper\" style=\"position: absolute;\"></div>",
        width: 221,
        height: 335,
        step: 0,
        interval: 5000,
        images: []
      };
      i = $.extend({}, m, p);
      b = $("#" + k);
      d = $(i.slider);
      a = $(i.wrapper);
      e = i.width;
      o = i.height;
      f = i.interval;
      h = (i.step ? i.step : e);
      n = i.images;
      j = n.length;
      g = "";
      c = 1;
      l = 0;
      while (l < j) {
        g += "<img src=\"" + n[l] + "\" width=\"" + e + "\" height=\"" + o + "\" style=\"float:left;\" />";
        l++;
      }
      a.html(g).css({
        width: e * j + j,
        height: o
      });
      d.css({
        width: e,
        height: o
      }).append(a);
      b.append(d);
      return setInterval((function() {
        var q;

        if (c === j) {
          a.animate({
            left: 0
          });
          return c = 1;
        } else {
          q = "-=" + h + "px";
          a.animate({
            left: q
          });
          return c++;
        }
      }), f);
    }
  });

  $(function() {
    var a, b, c, d, e, f, g, h, i, j;

    j = document;
    b = $("#features");
    c = 149;
    f = c * 7;
    g = true;
    a = "en";
    e = location.pathname.match(/\/(\w+)\/(\w*)/i);
    h = [];
    i = "/en/";
    if (e) {
      a = e[1] || a;
    }
    $("#feature_left").click(function() {
      if ((a === "ar" || a === "he") && g && parseInt(b.css("left"), 10) < f) {
        g = false;
        b.animate({
          left: "+=" + c
        }, function() {
          return g = true;
        });
        return;
      } else {
        if (a === "ar" || a === "he") {
          return;
        }
      }
      if (g && parseInt(b.css("left"), 10) < 0) {
        g = false;
        return b.animate({
          left: "+=" + c
        }, function() {
          return g = true;
        });
      }
    });
    $("#feature_right").click(function() {
      if ((a === "ar" || a === "he") && g && Math.abs(parseInt(b.css("left"), 10) > 0)) {
        g = false;
        b.animate({
          left: "-=" + c
        }, function() {
          return g = true;
        });
        return;
      } else {
        if (a === "ar" || a === "he") {
          return;
        }
      }
      if (g && Math.abs(parseInt(b.css("left"), 10)) < f) {
        g = false;
        return b.animate({
          left: "-=" + c
        }, function() {
          return g = true;
        });
      }
    });
    i = (a === "zh_TW" ? "/zh_TW/" : i);
    d = 1;
    while (d <= 3) {
      h.push(i + "img/banner/slider" + d + ".png");
      d++;
    }
    return $.slider("main", {
      images: h
    });
  });

}).call(this);
